version: '3.8'

services:
  flow-remote:
    build:
      context: "./"
      args:
        - INSTALL_MAKE=true
        - INSTALL_JDK=true
        - USE_OPENJDK=false
        - JDK_VERSION=17
        - INSTALL_MAVEN=true
        - INSTALL_NODE=true
        - NODE_VERSION=16
    image: "flow-remote:latest"
    container_name: "flow-remote"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./data:/data
    ports:
      - "2222:22"
      - "18000-18009:18000-18009"
